config/routes.rb
Rails.application.routes.draw do
  resources :tags

  root 'overview#index'

  get 'overview/ajax/:filter' => 'overview#_video'
  get 'overview/ajax/' => 'overview#_video'
  
  get 'overview/:filter' => 'overview#index'
  get 'overview/' => 'overview#index'

  get 'edit/:id' => 'edit#index'
  get 'edit/' => 'edit#index'

  post 'edit/' => 'edit#post'

end

app/models/acces_key.rb
class AccesKey < ActiveRecord::Base
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    has_many :videos_tags
    has_many :videos, :through => :videos_tags
end

app/models/video.rb
class Video < ActiveRecord::Base
    has_many :videos_tags
    has_many :tags, :through => :videos_tags
end

app/models/videos_tag.rb
class VideosTag < ActiveRecord::Base
    belongs_to :video
    belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_permissions

    
  private
  
  def set_permissions
    if params[:admin_hack] == AccesKey.first.key
        session[:admin] = 1
    end
    @admin = session[:admin]
  end

  def only_admin
    redirect_to "", alert: 'Sorry du hast keine Berechtigung...' if not session[:admin] == 1
  end
end

app/controllers/edit_controller.rb
class EditController < ApplicationController
    before_action :only_admin

    def index
        video_id = params[:id]

        if video_id
            @video = Video.find(video_id)
        else
            @video = Video.new
        end
        @tags = Tag.all
    end

    def post
        video_id = params[:id]
        if video_id.present?
            video = Video.find_or_create_by({:id => video_id})
        else
            video = Video.new
        end
        video.name = params[:name]
        video.description = params[:description]
        video.youtoobe_id = params[:youtoobe_id]
        video.save

        # Save activ Tags
        VideosTag.where(:video_id => video_id).destroy_all
        if params[:tag]
            puts "alle tags: "+params[:tag].inspect
            params[:tag].each do |tag|
                vt = VideosTag.new
                vt.video_id = video_id
                vt.tag_id = tag
                vt.save
            end
        end

        redirect_to action: "index", id: video.id
    end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
    def index
        tags = params[:filter]

        if tags
            @videos = Video.joins(:tags).where({"tags.id" => [tags]})
        else
            @videos = Video.joins('LEFT OUTER JOIN videos_tags ON videos.id = videos_tags.video_id')
        end

        @filter = Tag.all
    end

    def _video
        index
        render :layout => false
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]
  before_action :only_admin

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/edit_helper.rb
module EditHelper
end

app/helpers/overview_helper.rb
module OverviewHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/edit/index.html.erb
<%= form_tag("/edit", method: "post") do %>
<%= hidden_field_tag(:id, @video.id) %>
    <p>
      <%= label_tag(:name, "Titel:") %>
      <%= text_field_tag(:name, @video.name) %>
    </p>
    <p>
      <%= label_tag(:description, "Beschreibung:") %>
      <%= text_field_tag(:description, @video.description) %>
    </p>
    <p>
      <%= label_tag(:youtoobe_id, "Youtoobe ID (z.B. ahYd4t4vms8):") %>
      <%= text_field_tag(:youtoobe_id, @video.youtoobe_id) %>
    </p>
    <p>
        <% @tags.each do |tag| %>
            <% 
                # Check is active
                checked = false
                @video.tags.each do |activ_tag|
                    if activ_tag.id == tag.id
                        checked = true
                    end
                end
            %>

            <%= check_box_tag("tag[]", tag[:id], checked) %>
            <%= label_tag(:tag, tag[:name]) %>
        <% end %>
    </p>
    <%= submit_tag("Speichern") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VideoPortal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Übersicht",   '/' %></li>
        <li><%= link_to "Video erfassen",   '/edit' %></li>
        <li><%= link_to "Tags verwalten", '/tags' %></li>
      </ul>
    </nav>
    <%= yield %>

</body>
</html>

app/views/overview/_video.html.erb
<% @videos.each do |video| %>
  <p>
    <strong>Title:</strong>
    <%= video.name %>
  </p>
  <p>
    <strong>Beschreibung:</strong>
    <%= video.description %>
  </p>
  <p>
    <strong>Tags:</strong>
    <% video.tags.each do |tag| %>
      <%= tag.name %>
    <% end %>
  </p>
  <p>
      <iframe type='text/html' src='https://www.youtube.com/embed/<%= video.youtoobe_id %>' width='640' height='360' frameborder='0' allowfullscreen='true'></iframe>
  </p>
  <%= link_to 'Edit', "/edit/"+video.id.to_s if @admin %>
  <hr>
<% end %>

app/views/overview/index.html.erb
<script>
  $( document ).ready(function() {
    $('#tags_filter').submit(function() {  
      var valuesToSubmit = $(this).serialize();
      $.ajax({
          type: "GET",
          url: $(this).attr('action'), //sumbits it to the given url of the form
          data: valuesToSubmit,
      }).success(function(html){
          $('#video_container').html(html);
      });
      return false; // prevents normal behaviour
    });
  });
</script>

<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<%= form_tag("/overview/ajax/", id: "tags_filter", method: "get") do %>
  <fieldset>
    <legend>Filter</legend>
     <% @filter.each do |tag| %>
      <%= check_box_tag("filter[]", tag[:id]) %>
      <%= label_tag(:tag, tag[:name]) %>
    <% end %>
  </fieldset>
  <p><%= button_to "save and continue",{:class=>"savebutton"} %></p>
<%end%>


<div id="video_container">
  <%= render partial: "video", layout: "video" %>
</div>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>